### ISSUE TITLE
Choose your own adventure homework

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/choose_your_own_adventure_js#22]
I think that I understand the basics of this assignment, but I ran into several issues. Earlier on Wednesday evening, I was able to see and test my assignment in Chrome, but then I ran into some coding errors that prevented me from being able to preview the prompt. I thought some of the more complicated code, such as the integer response, might be causing the issue, so I deleted some of my code, but unfortunately the issues persisted and I ran out of time to figure it out. I also had an issue getting the git push origin master command to work, so I am just submitting what I have as a Gist.

https://gist.github.com/leighvarley/af902ccac45100c9dbe7#file-choose-your-own-adventure-homework

completeness: 3
comfort: 3
I would really appreciate any feedback as to where I went wrong and what needs to be corrected.

**Comment by RobertAKARobin** [comment]
It's hard to say at a glance. When this happens, rather than just deleting code, start a new document and copy in your code from your old document a bit at a time. Remember, the browser reads Javascript from the top down, so it makes sense to add in code a few lines at a time, from the top down. Once it stops working, you know where your error is!
